# Generated by Django 2.1.3 on 2018-11-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('sentiment_value', models.IntegerField(default=0)),
            ],
        ),
    ]
