# Generated by Django 2.1.3 on 2018-11-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='topic',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
